
utils::globalVariables(c(".SD", ".I", ".N", "groupe", "code_groupe",
                         "debut", "fin", ".id", "datetime", "date", "timestamp",
                         "date_heure", "start_date", "end_date", "updated_date",
                         "heure", "key", "V1", "value", "val_llim", "pmd", "comb_",
                         "val_vp", "code_essai", "val_vd", "val_asr", "val_and",
                         "date_1", "date_2", "date_3", "val_agp", "val_fortuit",
                         "val_indispo", "freq", "DATE_UTC", "couleurs",
                         "BALANCE", "COAL", "GAS", "H. ROR", "LIGNITE", "LOAD", "MISC. DTG", "MISC. NDG", "MIX. FUEL",
                         "NUCLEAR", "OIL", "ROW BAL.", "SOLAR", "WIND", "lac", "mcYear", "pump_d", "pump_w", "turb_d",
                         "turb_w", "jour", "variable", "area", "cluster", "ouvrage",
                         "country", "type",
                         "CHP", "Other", "Waste", "cogeneration_continue", "cogeneration_mdse_dispatchable_",
                         "file_name", "tz", "timeId",
                         "Total_fil_eau", "file_name", "hydraulique_fil_eau_eclusee", "hydraulique_tiers",
                         "groupe_hydro", "selection"))
